// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBltYo9IJxq0S5JeGz0SWuYHVsrSNL57tI',
    appId: '1:124314700873:web:7598cfa8db5037ff718398',
    messagingSenderId: '124314700873',
    projectId: 'group-116',
    authDomain: 'group-116.firebaseapp.com',
    storageBucket: 'group-116.appspot.com',
    measurementId: 'G-Q80E5BPXYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_dlQnqXlTnRTOxgQleFGPQrdPdFHtQwc',
    appId: '1:124314700873:android:821310f83ff80d35718398',
    messagingSenderId: '124314700873',
    projectId: 'group-116',
    storageBucket: 'group-116.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5yYclw2ggDGEEj0LONPMgU3VwhTfd1es',
    appId: '1:124314700873:ios:af0cda86bd6b624b718398',
    messagingSenderId: '124314700873',
    projectId: 'group-116',
    storageBucket: 'group-116.appspot.com',
    iosBundleId: 'com.eraasoft.taskApp116',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5yYclw2ggDGEEj0LONPMgU3VwhTfd1es',
    appId: '1:124314700873:ios:af0cda86bd6b624b718398',
    messagingSenderId: '124314700873',
    projectId: 'group-116',
    storageBucket: 'group-116.appspot.com',
    iosBundleId: 'com.eraasoft.taskApp116',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBltYo9IJxq0S5JeGz0SWuYHVsrSNL57tI',
    appId: '1:124314700873:web:1fe77d3363a462ad718398',
    messagingSenderId: '124314700873',
    projectId: 'group-116',
    authDomain: 'group-116.firebaseapp.com',
    storageBucket: 'group-116.appspot.com',
    measurementId: 'G-GPMWER6MFL',
  );
}
